# Generated by Django 3.0.5 on 2020-09-26 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=40000, null=True)),
                ('seed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
        ),
    ]
