# Generated by Django 3.0.5 on 2020-09-27 02:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), null=True, size=None),
        ),
        migrations.AddField(
            model_name='seed',
            name='r_idx',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seed',
            name='redditors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='seed',
            name='submissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), null=True, size=None),
        ),
        migrations.AddField(
            model_name='seed',
            name='subreddits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
