# Generated by Django 3.0.5 on 2020-10-04 11:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecosystem', '0002_auto_20200927_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='domain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
    ]
