# Generated by Django 3.0.5 on 2020-04-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=15)),
                ('client_secret', models.CharField(max_length=50)),
                ('user_agent', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
    ]
