# Generated by Django 3.0.5 on 2020-09-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='retrive_on',
            new_name='retrieved_on',
        ),
    ]
