# Generated by Django 3.0.5 on 2020-09-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20200927_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
