# Generated by Django 3.0.5 on 2020-09-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20200927_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
