# Generated by Django 3.0.5 on 2020-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20200927_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='url',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
