# Generated by Django 3.0.7 on 2020-10-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20201023_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='comments_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='submissions_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
